import LinkedList from "./linkedList"
let a = new LinkedList()
console.log(`init \n a => ${a.toString() || "''"} \n a.size => ${a.size()}`)
a.append(1)
console.log(`append 1 \n a => ${a.toString()} \n a.size => ${a.size()}`)
a.append(2)
console.log(`append 2 \n a => ${a.toString()} \n a.size => ${a.size()}`)
a.prepend(3)
console.log(`prepend 3 \n a => ${a.toString()} \n a.size => ${a.size()}`)
a.deleteHead()
console.log(`deleteHead \n a => ${a.toString()} \n a.size => ${a.size()}`)
a.prepend("hello World!")
console.log(`prepend helloworld \n a => ${a.toString()} \n a.size => ${a.size()}`)
a.delete(1)
console.log(`delete 1 \n a => ${a.toString()} \n a.size => ${a.size()}`)